version: "3.8"
services:
  node-app:
    container_name: express_node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app/src/:ro
    environment:
      - NODE_ENV=development
