version: "3.8"
services:
  node-app:
   build:
      context: .
      dockerfile: Dockerfile      
      target: prod 
      
   environment:
      - NOD_ENV=PROD
   command: ["npm","start"]
#   networks:
#    - app_network


#networks:
#  app_network:
#    driver: overlay
#    attachable: true
